name: n_localization_app
description: More easy way to use flutter_localizations plugin. Multi-platforms are supported.
version: 0.0.1
repository: https://github.com/NaingMyoThawNMYT/n_localization_app.git

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
